#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.23a
#  in conjunction with Tcl version 8.6
#    Jun 23, 2019 12:53:52 AM CST  platform: Windows NT
# Create By Rafie

import sys

from matplotlib.figure import Figure

try:
    import csv
    import pandas as pd
    import Tkinter as tk
    import os
    import librosa
    from PIL import ImageTk, Image
    import scipy.io.wavfile
    from scipy.fftpack import dct
    from sklearn.externals import joblib
    from sklearn.base import BaseEstimator, ClassifierMixin

except ImportError:
    import csv
    import pandas as pd
    import tkinter as tk
    import librosa
    from tkinter import *
    from tkinter.filedialog import askopenfilename
    import matplotlib
    import scipy.io.wavfile
    from scipy.fftpack import dct
    from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
    import matplotlib.pyplot as plt
    import numpy as np
    from sklearn.externals import joblib
    from sklearn.base import BaseEstimator, ClassifierMixin
    from sklearn.preprocessing import LabelEncoder, StandardScaler

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
import myklasifikasi_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    myklasifikasi_support.init(root, top)
    root.mainloop()

w = None
filename="He"
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    myklasifikasi_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

def schart2():

    sample_rate, signal = scipy.io.wavfile.read(filename)

    signal = signal[0:int(3.5 * sample_rate)]
    # plt.subplot(221)
    # plt.plot(signal)
    # plt.xlabel('Time')
    # plt.ylabel('Amplitude')
    # plt.title('Signal dalam Time Domain')
    # plt.show()

def chartemphasis():
    sample_rate, signal = scipy.io.wavfile.read(filename)
    signal = signal[0:int(3.5 * sample_rate)]
  #  plt.figure(figsize=(5, 3))
    plt.subplot(211)
    plt.plot(signal)
    plt.xlabel('Time')
    plt.ylabel('Amplitude')
    plt.title('Signal dalam Time Domain')

    pre_emphasis = 0.97
    emphasized_signal = np.append(signal[0], signal[1:] - pre_emphasis * signal[:-1])
   # plt.figure(figsize=(5, 3))
    plt.subplot(212)
    plt.plot(emphasized_signal)
    plt.xlabel('Time')
    plt.ylabel('Amplitude')
    plt.title('Signal dalam Time Domain Sesudah Pre-Emphasis')
    plt.show()

class Toplevel1:


    def open_file(self):
        global filename
        print(self.EntryM1.delete(0, END))
        print(self.EntryM2.delete(0, END))
        print(self.EntryM3.delete(0, END))
        print(self.EntryM4.delete(0, END))
        print(self.EntryM5.delete(0, END))
        print(self.EntryM6.delete(0, END))
        print(self.EntryM7.delete(0, END))
        print(self.EntryM8.delete(0, END))
        print(self.EntryM9.delete(0, END))
        print(self.EntryM10.delete(0, END))
        print(self.EntryM11.delete(0, END))
        print(self.EntryM12.delete(0, END))
        print(self.EntryM13.delete(0, END))
        print(self.EntryM14.delete(0, END))
        print(self.EntryM15.delete(0, END))
        print(self.EntryM16.delete(0, END))
        print(self.EntryM17.delete(0, END))
        print(self.EntryM18.delete(0, END))
        print(self.EntryM19.delete(0, END))
        print(self.EntryM20.delete(0, END))
        print(self.EntryChroma.delete(0, END))
        print(self.EntryRMSE.delete(0, END))
        print(self.EntryCentroid.delete(0, END))
        print(self.EntryBandwidth.delete(0, END))
        print(self.EntryZeroCross.delete(0, END))
        print(self.Entry1.delete(0, END))

        filename = askopenfilename(initialdir='D:\\', title="Pilih Audio",
                                   filetypes=(("Audio Files", ".wav"), ("All Files", "*.*")))
        print(self.TEntry1.delete(0,END))
        print(self.TEntry1.insert(0,filename))
        schart2()

    def preemphasis(self):
        chartemphasis()

    def ektraksi(self):
        y, sr = librosa.load(filename, mono=True, duration=30)
        chroma_stft = librosa.feature.chroma_stft(y=y, sr=sr)
        spec_cent = librosa.feature.spectral_centroid(y=y, sr=sr)
        spec_bw = librosa.feature.spectral_bandwidth(y=y, sr=sr)
        #  rolloff = librosa.feature.spectral_rolloff(y=y, sr=sr)
        mfcc = librosa.feature.mfcc(y=y, sr=sr)

        rmse = librosa.feature.rmse(y)
        zcr = librosa.feature.zero_crossing_rate(y)
        rt_chroma = np.mean(chroma_stft)
        rt_rmse = np.mean(rmse)
        rt_sc = np.mean(spec_cent)
        rt_sb = np.mean(spec_bw)
        rt_zc = np.mean(zcr)

        my_list = []
        my_list.clear()
        for e in mfcc:
            my_list.append(np.mean(e))
            #print(np.mean(e))

        print(self.EntryM1.delete(0,END))
        print(self.EntryM2.delete(0,END))
        print(self.EntryM3.delete(0,END))
        print(self.EntryM4.delete(0,END))
        print(self.EntryM5.delete(0,END))
        print(self.EntryM6.delete(0,END))
        print(self.EntryM7.delete(0,END))
        print(self.EntryM8.delete(0,END))
        print(self.EntryM9.delete(0,END))
        print(self.EntryM10.delete(0,END))
        print(self.EntryM11.delete(0,END))
        print(self.EntryM12.delete(0,END))
        print(self.EntryM13.delete(0,END))
        print(self.EntryM14.delete(0,END))
        print(self.EntryM15.delete(0,END))
        print(self.EntryM16.delete(0,END))
        print(self.EntryM17.delete(0,END))
        print(self.EntryM18.delete(0,END))
        print(self.EntryM19.delete(0,END))
        print(self.EntryM20.delete(0,END))
        print(self.Entry1.delete(0, END))

        print(self.EntryM1.insert(0,my_list[0]))
        print(self.EntryM2.insert(0,my_list[1]))
        print(self.EntryM3.insert(0,my_list[2]))
        print(self.EntryM4.insert(0,my_list[3]))
        print(self.EntryM5.insert(0,my_list[4]))
        print(self.EntryM6.insert(0,my_list[5]))
        print(self.EntryM7.insert(0,my_list[6]))
        print(self.EntryM8.insert(0,my_list[7]))
        print(self.EntryM9.insert(0,my_list[8]))
        print(self.EntryM10.insert(0,my_list[9]))
        print(self.EntryM11.insert(0,my_list[10]))
        print(self.EntryM12.insert(0,my_list[11]))
        print(self.EntryM13.insert(0,my_list[12]))
        print(self.EntryM14.insert(0,my_list[13]))
        print(self.EntryM15.insert(0,my_list[14]))
        print(self.EntryM16.insert(0,my_list[15]))
        print(self.EntryM17.insert(0,my_list[16]))
        print(self.EntryM18.insert(0,my_list[17]))
        print(self.EntryM19.insert(0,my_list[18]))
        print(self.EntryM20.insert(0,my_list[19]))

        print(self.EntryChroma.delete(0, END))
        print(self.EntryRMSE.delete(0, END))
        print(self.EntryCentroid.delete(0, END))
        print(self.EntryBandwidth.delete(0, END))
        print(self.EntryZeroCross.delete(0, END))

        print(self.EntryChroma.insert(0,rt_chroma))
        print(self.EntryRMSE.insert(0,rt_rmse))
        print(self.EntryCentroid.insert(0, rt_sc))
        print(self.EntryBandwidth.insert(0, rt_sb))
        print(self.EntryZeroCross.insert(0,rt_zc))


    def klasifikasi(self):
        m1 = self.EntryM1.get();
        m2 = self.EntryM2.get();
        m3 = self.EntryM3.get();
        m4 = self.EntryM4.get();
        m5 = self.EntryM5.get();
        m6 = self.EntryM6.get();
        m7 = self.EntryM7.get();
        m8 = self.EntryM8.get();
        m9 = self.EntryM9.get();
        m10 = self.EntryM10.get();
        m11 = self.EntryM11.get();
        m12 = self.EntryM12.get();
        m13 = self.EntryM13.get();
        m14 = self.EntryM14.get();
        m15 = self.EntryM15.get();
        m16 = self.EntryM16.get();
        m17 = self.EntryM17.get();
        m18 = self.EntryM18.get();
        m19 = self.EntryM19.get();
        m20 = self.EntryM20.get();
        chr = self.EntryChroma.get();
        rmse = self.EntryRMSE.get();
        zero = self.EntryZeroCross.get();
        cent = self.EntryCentroid.get();
        band = self.EntryBandwidth.get();

        dframe = pd.DataFrame({'chr': [chr],
                           'rmse': [rmse],
                           'cent': [cent],
                           'band': [band],
                           'zero': [zero],
                           'm1':[m1],
                           'm2': [m2],
                           'm3': [m3],
                           'm4': [m4],
                           'm5': [m5],
                           'm6': [m6],
                           'm7': [m7],
                           'm8': [m8],
                           'm9': [m9],
                           'm10': [m10],
                           'm11': [m11],
                           'm12': [m12],
                           'm13': [m13],
                           'm14': [m14],
                           'm15': [m15],
                           'm16': [m16],
                           'm17': [m17],
                           'm18': [m18],
                           'm19': [m19],
                           'm20': [m20]
                           })

        model = joblib.load('D:/KULIAH/Digital Signal Processing/Identification Logat/model_ku.pkl')
     #   print(model)
        prediksi = model.predict(dframe)
        print(prediksi)
        if prediksi == 0:
            hasil = "Banjar Hulu"
        elif prediksi == 1:
            hasil ="Banjar Kuala"
        elif prediksi == 2:
            hasil = "Dayak Bakumpai"
        elif prediksi == 3:
            hasil = "Dayak Ngaju"
        else:
            hasil="Tidak Diketahui"

        print(self.Entry1.delete(0,END))
        print(self.Entry1.insert(0,hasil))

    def __init__(self, top=None):
            '''This class configures and populates the toplevel window.
               top is the toplevel containing window.'''
            _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
            _fgcolor = '#000000'  # X11 color: 'black'
            _compcolor = '#d9d9d9'  # X11 color: 'gray85'
            _ana1color = '#d9d9d9'  # X11 color: 'gray85'
            _ana2color = '#ececec'  # Closest X11 color: 'gray92'
            font10 = "-family {Courier New} -size 10 -weight normal -slant" \
                     " roman -underline 0 -overstrike 0"
            self.style = ttk.Style()
            if sys.platform == "win32":
                self.style.theme_use('winnative')
            self.style.configure('.', background=_bgcolor)
            self.style.configure('.', foreground=_fgcolor)
            self.style.configure('.', font="TkDefaultFont")
            self.style.map('.', background=
            [('selected', _compcolor), ('active', _ana2color)])

            top.geometry("879x585+250+87")
            top.title("Machine Learning : Identifkasi Suku dari Suara dengan PCA-SVM")
            top.configure(background="#d9d9d9")
            top.configure(highlightbackground="#d9d9d9")
            top.configure(highlightcolor="black")

            self.TFrame1 = ttk.Frame(top)
            self.TFrame1.place(relx=0.0, rely=0.017, relheight=0.111, relwidth=0.984)

            self.TFrame1.configure(relief='groove')
            self.TFrame1.configure(borderwidth="2")
            self.TFrame1.configure(relief="groove")
            self.TFrame1.configure(width=865)

            self.Button1 = tk.Button(self.TFrame1)
            self.Button1.place(relx=0.012, rely=0.154, height=34, width=130)
            self.Button1.configure(activebackground="#ececec")
            self.Button1.configure(activeforeground="#000000")
            self.Button1.configure(background="#d9d9d9")
            self.Button1.configure(disabledforeground="#a3a3a3")
            self.Button1.configure(foreground="#000000")
            self.Button1.configure(command=self.open_file)
            self.Button1.configure(highlightbackground="#d9d9d9")
            self.Button1.configure(highlightcolor="black")
            self.Button1.configure(pady="0")
            self.Button1.configure(text='''Pilih Audio File''')

            self.TEntry1 = ttk.Entry(self.TFrame1)
            self.TEntry1.place(relx=0.185, rely=0.154, relheight=0.477
                               , relwidth=0.215)
            self.TEntry1.configure(takefocus="")
            self.TEntry1.configure(cursor="ibeam")

            self.Button2 = tk.Button(self.TFrame1)
            self.Button2.place(relx=0.416, rely=0.154, height=34, width=97)
            self.Button2.configure(activebackground="#ececec")
            self.Button2.configure(activeforeground="#000000")
            self.Button2.configure(background="#d9d9d9")
            self.Button2.configure(disabledforeground="#a3a3a3")
            self.Button2.configure(command=self.preemphasis)
            self.Button2.configure(foreground="#000000")
            self.Button2.configure(highlightbackground="#d9d9d9")
            self.Button2.configure(highlightcolor="black")
            self.Button2.configure(pady="0")
            self.Button2.configure(text='''Pre-Emphasis''')

            self.Button3 = tk.Button(self.TFrame1)
            self.Button3.place(relx=0.543, rely=0.154, height=34, width=97)
            self.Button3.configure(activebackground="#ececec")
            self.Button3.configure(activeforeground="#000000")
            self.Button3.configure(background="#d9d9d9")
            self.Button3.configure(disabledforeground="#a3a3a3")
            self.Button3.configure(foreground="#000000")
            self.Button3.configure(command=self.ektraksi)
            self.Button3.configure(highlightbackground="#d9d9d9")
            self.Button3.configure(highlightcolor="black")
            self.Button3.configure(pady="0")
            self.Button3.configure(text='''Ektraksi Fitur''')

            self.Button4 = tk.Button(self.TFrame1)
            self.Button4.place(relx=0.671, rely=0.154, height=34, width=97)
            self.Button4.configure(activebackground="#ececec")
            self.Button4.configure(activeforeground="#000000")
            self.Button4.configure(background="#d9d9d9")
            self.Button4.configure(disabledforeground="#a3a3a3")
            self.Button4.configure(foreground="#000000")
            self.Button4.configure(command=self.klasifikasi)
            self.Button4.configure(highlightbackground="#d9d9d9")
            self.Button4.configure(highlightcolor="black")
            self.Button4.configure(pady="0")
            self.Button4.configure(text='''Klasifikasi''')


            self.Label3 = tk.Label(top)
            self.Label3.place(relx=0.011, rely=0.718, height=21, width=86)
            self.Label3.configure(activebackground="#f9f9f9")
            self.Label3.configure(activeforeground="black")
            self.Label3.configure(background="#d9d9d9")
            self.Label3.configure(disabledforeground="#a3a3a3")
            self.Label3.configure(foreground="#000000")
            self.Label3.configure(highlightbackground="#d9d9d9")
            self.Label3.configure(highlightcolor="black")
            self.Label3.configure(text='''Hasil Klasifikasi''')

            self.Entry1 = tk.Entry(top)
            self.Entry1.place(relx=0.125, rely=0.718, height=20, relwidth=0.187)
            self.Entry1.configure(background="white")
            self.Entry1.configure(disabledforeground="#a3a3a3")
            self.Entry1.configure(font="TkFixedFont")
            self.Entry1.configure(foreground="#000000")
            self.Entry1.configure(highlightbackground="#d9d9d9")
            self.Entry1.configure(highlightcolor="black")
            self.Entry1.configure(insertbackground="black")
            self.Entry1.configure(selectbackground="#c4c4c4")
            self.Entry1.configure(selectforeground="black")

            self.Labelframe1 = tk.LabelFrame(top)
            self.Labelframe1.place(relx=0.011, rely=0.137, relheight=0.573
                                   , relwidth=0.978)
            self.Labelframe1.configure(relief='groove')
            self.Labelframe1.configure(foreground="black")
            self.Labelframe1.configure(text='''Hasil Ektraksi Fitur''')
            self.Labelframe1.configure(background="#d9d9d9")
            self.Labelframe1.configure(width=860)

            self.Label1 = tk.Label(self.Labelframe1)
            self.Label1.place(relx=0.023, rely=0.09, height=21, width=88
                              , bordermode='ignore')
            self.Label1.configure(background="#d9d9d9")
            self.Label1.configure(disabledforeground="#a3a3a3")
            self.Label1.configure(foreground="#000000")
            self.Label1.configure(text='''MFCC 1''')
            self.Label1.configure(width=88)

            self.Label1_1 = tk.Label(self.Labelframe1)
            self.Label1_1.place(relx=0.047, rely=0.179, height=21, width=48
                                , bordermode='ignore')
            self.Label1_1.configure(activebackground="#f9f9f9")
            self.Label1_1.configure(activeforeground="black")
            self.Label1_1.configure(background="#d9d9d9")
            self.Label1_1.configure(disabledforeground="#a3a3a3")
            self.Label1_1.configure(foreground="#000000")
            self.Label1_1.configure(highlightbackground="#d9d9d9")
            self.Label1_1.configure(highlightcolor="black")
            self.Label1_1.configure(text='''MFCC 2''')

            self.EntryM1 = tk.Entry(self.Labelframe1)
            self.EntryM1.place(relx=0.128, rely=0.09, height=20, relwidth=0.191
                               , bordermode='ignore')
            self.EntryM1.configure(background="white")
            self.EntryM1.configure(disabledforeground="#a3a3a3")
            self.EntryM1.configure(font=font10)
            self.EntryM1.configure(foreground="#000000")
            self.EntryM1.configure(insertbackground="black")

            self.Label1_2 = tk.Label(self.Labelframe1)
            self.Label1_2.place(relx=0.047, rely=0.269, height=21, width=48
                                , bordermode='ignore')
            self.Label1_2.configure(activebackground="#f9f9f9")
            self.Label1_2.configure(activeforeground="black")
            self.Label1_2.configure(background="#d9d9d9")
            self.Label1_2.configure(disabledforeground="#a3a3a3")
            self.Label1_2.configure(foreground="#000000")
            self.Label1_2.configure(highlightbackground="#d9d9d9")
            self.Label1_2.configure(highlightcolor="black")
            self.Label1_2.configure(text='''MFCC 3''')

            self.Label1_2 = tk.Label(self.Labelframe1)
            self.Label1_2.place(relx=0.047, rely=0.358, height=21, width=48
                                , bordermode='ignore')
            self.Label1_2.configure(activebackground="#f9f9f9")
            self.Label1_2.configure(activeforeground="black")
            self.Label1_2.configure(background="#d9d9d9")
            self.Label1_2.configure(disabledforeground="#a3a3a3")
            self.Label1_2.configure(foreground="#000000")
            self.Label1_2.configure(highlightbackground="#d9d9d9")
            self.Label1_2.configure(highlightcolor="black")
            self.Label1_2.configure(text='''MFCC 4''')

            self.Label1_2 = tk.Label(self.Labelframe1)
            self.Label1_2.place(relx=0.047, rely=0.448, height=21, width=48
                                , bordermode='ignore')
            self.Label1_2.configure(activebackground="#f9f9f9")
            self.Label1_2.configure(activeforeground="black")
            self.Label1_2.configure(background="#d9d9d9")
            self.Label1_2.configure(disabledforeground="#a3a3a3")
            self.Label1_2.configure(foreground="#000000")
            self.Label1_2.configure(highlightbackground="#d9d9d9")
            self.Label1_2.configure(highlightcolor="black")
            self.Label1_2.configure(text='''MFCC 5''')
            self.Label1_2.configure(width=48)

            self.Label1_2 = tk.Label(self.Labelframe1)
            self.Label1_2.place(relx=0.047, rely=0.537, height=21, width=48
                                , bordermode='ignore')
            self.Label1_2.configure(activebackground="#f9f9f9")
            self.Label1_2.configure(activeforeground="black")
            self.Label1_2.configure(background="#d9d9d9")
            self.Label1_2.configure(disabledforeground="#a3a3a3")
            self.Label1_2.configure(foreground="#000000")
            self.Label1_2.configure(highlightbackground="#d9d9d9")
            self.Label1_2.configure(highlightcolor="black")
            self.Label1_2.configure(text='''MFCC 6''')

            self.Label1_2 = tk.Label(self.Labelframe1)
            self.Label1_2.place(relx=0.047, rely=0.627, height=21, width=48
                                , bordermode='ignore')
            self.Label1_2.configure(activebackground="#f9f9f9")
            self.Label1_2.configure(activeforeground="black")
            self.Label1_2.configure(background="#d9d9d9")
            self.Label1_2.configure(disabledforeground="#a3a3a3")
            self.Label1_2.configure(foreground="#000000")
            self.Label1_2.configure(highlightbackground="#d9d9d9")
            self.Label1_2.configure(highlightcolor="black")
            self.Label1_2.configure(text='''MFCC 7''')

            self.Label1_2 = tk.Label(self.Labelframe1)
            self.Label1_2.place(relx=0.047, rely=0.716, height=21, width=48
                                , bordermode='ignore')
            self.Label1_2.configure(activebackground="#f9f9f9")
            self.Label1_2.configure(activeforeground="black")
            self.Label1_2.configure(background="#d9d9d9")
            self.Label1_2.configure(disabledforeground="#a3a3a3")
            self.Label1_2.configure(foreground="#000000")
            self.Label1_2.configure(highlightbackground="#d9d9d9")
            self.Label1_2.configure(highlightcolor="black")
            self.Label1_2.configure(text='''MFCC 8''')

            self.Label1_2 = tk.Label(self.Labelframe1)
            self.Label1_2.place(relx=0.047, rely=0.806, height=21, width=48
                                , bordermode='ignore')
            self.Label1_2.configure(activebackground="#f9f9f9")
            self.Label1_2.configure(activeforeground="black")
            self.Label1_2.configure(background="#d9d9d9")
            self.Label1_2.configure(disabledforeground="#a3a3a3")
            self.Label1_2.configure(foreground="#000000")
            self.Label1_2.configure(highlightbackground="#d9d9d9")
            self.Label1_2.configure(highlightcolor="black")
            self.Label1_2.configure(text='''MFCC 9''')

            self.Label1_2 = tk.Label(self.Labelframe1)
            self.Label1_2.place(relx=0.047, rely=0.896, height=21, width=48
                                , bordermode='ignore')
            self.Label1_2.configure(activebackground="#f9f9f9")
            self.Label1_2.configure(activeforeground="black")
            self.Label1_2.configure(background="#d9d9d9")
            self.Label1_2.configure(disabledforeground="#a3a3a3")
            self.Label1_2.configure(foreground="#000000")
            self.Label1_2.configure(highlightbackground="#d9d9d9")
            self.Label1_2.configure(highlightcolor="black")
            self.Label1_2.configure(text='''MFCC 10''')

            self.EntryM2 = tk.Entry(self.Labelframe1)
            self.EntryM2.place(relx=0.128, rely=0.179, height=20, relwidth=0.191
                               , bordermode='ignore')
            self.EntryM2.configure(background="white")
            self.EntryM2.configure(disabledforeground="#a3a3a3")
            self.EntryM2.configure(font=font10)
            self.EntryM2.configure(foreground="#000000")
            self.EntryM2.configure(highlightbackground="#d9d9d9")
            self.EntryM2.configure(highlightcolor="black")
            self.EntryM2.configure(insertbackground="black")
            self.EntryM2.configure(selectbackground="#c4c4c4")
            self.EntryM2.configure(selectforeground="black")

            self.EntryM3 = tk.Entry(self.Labelframe1)
            self.EntryM3.place(relx=0.128, rely=0.269, height=20, relwidth=0.191
                               , bordermode='ignore')
            self.EntryM3.configure(background="white")
            self.EntryM3.configure(disabledforeground="#a3a3a3")
            self.EntryM3.configure(font=font10)
            self.EntryM3.configure(foreground="#000000")
            self.EntryM3.configure(highlightbackground="#d9d9d9")
            self.EntryM3.configure(highlightcolor="black")
            self.EntryM3.configure(insertbackground="black")
            self.EntryM3.configure(selectbackground="#c4c4c4")
            self.EntryM3.configure(selectforeground="black")

            self.EntryM4 = tk.Entry(self.Labelframe1)
            self.EntryM4.place(relx=0.128, rely=0.358, height=20, relwidth=0.191
                               , bordermode='ignore')
            self.EntryM4.configure(background="white")
            self.EntryM4.configure(disabledforeground="#a3a3a3")
            self.EntryM4.configure(font=font10)
            self.EntryM4.configure(foreground="#000000")
            self.EntryM4.configure(highlightbackground="#d9d9d9")
            self.EntryM4.configure(highlightcolor="black")
            self.EntryM4.configure(insertbackground="black")
            self.EntryM4.configure(selectbackground="#c4c4c4")
            self.EntryM4.configure(selectforeground="black")

            self.EntryM5 = tk.Entry(self.Labelframe1)
            self.EntryM5.place(relx=0.128, rely=0.448, height=20, relwidth=0.191
                               , bordermode='ignore')
            self.EntryM5.configure(background="white")
            self.EntryM5.configure(disabledforeground="#a3a3a3")
            self.EntryM5.configure(font=font10)
            self.EntryM5.configure(foreground="#000000")
            self.EntryM5.configure(highlightbackground="#d9d9d9")
            self.EntryM5.configure(highlightcolor="black")
            self.EntryM5.configure(insertbackground="black")
            self.EntryM5.configure(selectbackground="#c4c4c4")
            self.EntryM5.configure(selectforeground="black")

            self.EntryM6 = tk.Entry(self.Labelframe1)
            self.EntryM6.place(relx=0.128, rely=0.537, height=20, relwidth=0.191
                               , bordermode='ignore')
            self.EntryM6.configure(background="white")
            self.EntryM6.configure(disabledforeground="#a3a3a3")
            self.EntryM6.configure(font=font10)
            self.EntryM6.configure(foreground="#000000")
            self.EntryM6.configure(highlightbackground="#d9d9d9")
            self.EntryM6.configure(highlightcolor="black")
            self.EntryM6.configure(insertbackground="black")
            self.EntryM6.configure(selectbackground="#c4c4c4")
            self.EntryM6.configure(selectforeground="black")

            self.EntryM7 = tk.Entry(self.Labelframe1)
            self.EntryM7.place(relx=0.128, rely=0.627, height=20, relwidth=0.191
                               , bordermode='ignore')
            self.EntryM7.configure(background="white")
            self.EntryM7.configure(disabledforeground="#a3a3a3")
            self.EntryM7.configure(font=font10)
            self.EntryM7.configure(foreground="#000000")
            self.EntryM7.configure(highlightbackground="#d9d9d9")
            self.EntryM7.configure(highlightcolor="black")
            self.EntryM7.configure(insertbackground="black")
            self.EntryM7.configure(selectbackground="#c4c4c4")
            self.EntryM7.configure(selectforeground="black")

            self.EntryM8 = tk.Entry(self.Labelframe1)
            self.EntryM8.place(relx=0.128, rely=0.716, height=20, relwidth=0.191
                               , bordermode='ignore')
            self.EntryM8.configure(background="white")
            self.EntryM8.configure(disabledforeground="#a3a3a3")
            self.EntryM8.configure(font=font10)
            self.EntryM8.configure(foreground="#000000")
            self.EntryM8.configure(highlightbackground="#d9d9d9")
            self.EntryM8.configure(highlightcolor="black")
            self.EntryM8.configure(insertbackground="black")
            self.EntryM8.configure(selectbackground="#c4c4c4")
            self.EntryM8.configure(selectforeground="black")

            self.EntryM9 = tk.Entry(self.Labelframe1)
            self.EntryM9.place(relx=0.128, rely=0.806, height=20, relwidth=0.191
                               , bordermode='ignore')
            self.EntryM9.configure(background="white")
            self.EntryM9.configure(disabledforeground="#a3a3a3")
            self.EntryM9.configure(font=font10)
            self.EntryM9.configure(foreground="#000000")
            self.EntryM9.configure(highlightbackground="#d9d9d9")
            self.EntryM9.configure(highlightcolor="black")
            self.EntryM9.configure(insertbackground="black")
            self.EntryM9.configure(selectbackground="#c4c4c4")
            self.EntryM9.configure(selectforeground="black")

            self.EntryM10 = tk.Entry(self.Labelframe1)
            self.EntryM10.place(relx=0.128, rely=0.896, height=20, relwidth=0.191
                                , bordermode='ignore')
            self.EntryM10.configure(background="white")
            self.EntryM10.configure(disabledforeground="#a3a3a3")
            self.EntryM10.configure(font=font10)
            self.EntryM10.configure(foreground="#000000")
            self.EntryM10.configure(highlightbackground="#d9d9d9")
            self.EntryM10.configure(highlightcolor="black")
            self.EntryM10.configure(insertbackground="black")
            self.EntryM10.configure(selectbackground="#c4c4c4")
            self.EntryM10.configure(selectforeground="black")

            self.Label2 = tk.Label(self.Labelframe1)
            self.Label2.place(relx=0.36, rely=0.09, height=21, width=54
                              , bordermode='ignore')
            self.Label2.configure(background="#d9d9d9")
            self.Label2.configure(disabledforeground="#a3a3a3")
            self.Label2.configure(foreground="#000000")
            self.Label2.configure(text='''MFCC 11''')

            self.EntryM11 = tk.Entry(self.Labelframe1)
            self.EntryM11.place(relx=0.442, rely=0.09, height=20, relwidth=0.191
                                , bordermode='ignore')
            self.EntryM11.configure(background="white")
            self.EntryM11.configure(disabledforeground="#a3a3a3")
            self.EntryM11.configure(font=font10)
            self.EntryM11.configure(foreground="#000000")
            self.EntryM11.configure(highlightbackground="#d9d9d9")
            self.EntryM11.configure(highlightcolor="black")
            self.EntryM11.configure(insertbackground="black")
            self.EntryM11.configure(selectbackground="#c4c4c4")
            self.EntryM11.configure(selectforeground="black")

            self.EntryM12 = tk.Entry(self.Labelframe1)
            self.EntryM12.place(relx=0.442, rely=0.179, height=20, relwidth=0.191
                                , bordermode='ignore')
            self.EntryM12.configure(background="white")
            self.EntryM12.configure(disabledforeground="#a3a3a3")
            self.EntryM12.configure(font=font10)
            self.EntryM12.configure(foreground="#000000")
            self.EntryM12.configure(highlightbackground="#d9d9d9")
            self.EntryM12.configure(highlightcolor="black")
            self.EntryM12.configure(insertbackground="black")
            self.EntryM12.configure(selectbackground="#c4c4c4")
            self.EntryM12.configure(selectforeground="black")

            self.EntryM13 = tk.Entry(self.Labelframe1)
            self.EntryM13.place(relx=0.442, rely=0.269, height=20, relwidth=0.191
                                , bordermode='ignore')
            self.EntryM13.configure(background="white")
            self.EntryM13.configure(disabledforeground="#a3a3a3")
            self.EntryM13.configure(font=font10)
            self.EntryM13.configure(foreground="#000000")
            self.EntryM13.configure(highlightbackground="#d9d9d9")
            self.EntryM13.configure(highlightcolor="black")
            self.EntryM13.configure(insertbackground="black")
            self.EntryM13.configure(selectbackground="#c4c4c4")
            self.EntryM13.configure(selectforeground="black")

            self.EntryM14 = tk.Entry(self.Labelframe1)
            self.EntryM14.place(relx=0.442, rely=0.358, height=20, relwidth=0.191
                                , bordermode='ignore')
            self.EntryM14.configure(background="white")
            self.EntryM14.configure(disabledforeground="#a3a3a3")
            self.EntryM14.configure(font=font10)
            self.EntryM14.configure(foreground="#000000")
            self.EntryM14.configure(highlightbackground="#d9d9d9")
            self.EntryM14.configure(highlightcolor="black")
            self.EntryM14.configure(insertbackground="black")
            self.EntryM14.configure(selectbackground="#c4c4c4")
            self.EntryM14.configure(selectforeground="black")

            self.EntryM15 = tk.Entry(self.Labelframe1)
            self.EntryM15.place(relx=0.442, rely=0.448, height=20, relwidth=0.191
                                , bordermode='ignore')
            self.EntryM15.configure(background="white")
            self.EntryM15.configure(disabledforeground="#a3a3a3")
            self.EntryM15.configure(font=font10)
            self.EntryM15.configure(foreground="#000000")
            self.EntryM15.configure(highlightbackground="#d9d9d9")
            self.EntryM15.configure(highlightcolor="black")
            self.EntryM15.configure(insertbackground="black")
            self.EntryM15.configure(selectbackground="#c4c4c4")
            self.EntryM15.configure(selectforeground="black")

            self.EntryM16 = tk.Entry(self.Labelframe1)
            self.EntryM16.place(relx=0.442, rely=0.537, height=20, relwidth=0.191
                                , bordermode='ignore')
            self.EntryM16.configure(background="white")
            self.EntryM16.configure(disabledforeground="#a3a3a3")
            self.EntryM16.configure(font=font10)
            self.EntryM16.configure(foreground="#000000")
            self.EntryM16.configure(highlightbackground="#d9d9d9")
            self.EntryM16.configure(highlightcolor="black")
            self.EntryM16.configure(insertbackground="black")
            self.EntryM16.configure(selectbackground="#c4c4c4")
            self.EntryM16.configure(selectforeground="black")

            self.EntryM17 = tk.Entry(self.Labelframe1)
            self.EntryM17.place(relx=0.442, rely=0.627, height=20, relwidth=0.191
                                , bordermode='ignore')
            self.EntryM17.configure(background="white")
            self.EntryM17.configure(disabledforeground="#a3a3a3")
            self.EntryM17.configure(font=font10)
            self.EntryM17.configure(foreground="#000000")
            self.EntryM17.configure(highlightbackground="#d9d9d9")
            self.EntryM17.configure(highlightcolor="black")
            self.EntryM17.configure(insertbackground="black")
            self.EntryM17.configure(selectbackground="#c4c4c4")
            self.EntryM17.configure(selectforeground="black")

            self.EntryM18 = tk.Entry(self.Labelframe1)
            self.EntryM18.place(relx=0.442, rely=0.716, height=20, relwidth=0.191
                                , bordermode='ignore')
            self.EntryM18.configure(background="white")
            self.EntryM18.configure(disabledforeground="#a3a3a3")
            self.EntryM18.configure(font=font10)
            self.EntryM18.configure(foreground="#000000")
            self.EntryM18.configure(highlightbackground="#d9d9d9")
            self.EntryM18.configure(highlightcolor="black")
            self.EntryM18.configure(insertbackground="black")
            self.EntryM18.configure(selectbackground="#c4c4c4")
            self.EntryM18.configure(selectforeground="black")

            self.EntryM19 = tk.Entry(self.Labelframe1)
            self.EntryM19.place(relx=0.442, rely=0.806, height=20, relwidth=0.191
                                , bordermode='ignore')
            self.EntryM19.configure(background="white")
            self.EntryM19.configure(disabledforeground="#a3a3a3")
            self.EntryM19.configure(font=font10)
            self.EntryM19.configure(foreground="#000000")
            self.EntryM19.configure(highlightbackground="#d9d9d9")
            self.EntryM19.configure(highlightcolor="black")
            self.EntryM19.configure(insertbackground="black")
            self.EntryM19.configure(selectbackground="#c4c4c4")
            self.EntryM19.configure(selectforeground="black")

            self.EntryM20 = tk.Entry(self.Labelframe1)
            self.EntryM20.place(relx=0.442, rely=0.896, height=20, relwidth=0.191
                                , bordermode='ignore')
            self.EntryM20.configure(background="white")
            self.EntryM20.configure(disabledforeground="#a3a3a3")
            self.EntryM20.configure(font=font10)
            self.EntryM20.configure(foreground="#000000")
            self.EntryM20.configure(highlightbackground="#d9d9d9")
            self.EntryM20.configure(highlightcolor="black")
            self.EntryM20.configure(insertbackground="black")
            self.EntryM20.configure(selectbackground="#c4c4c4")
            self.EntryM20.configure(selectforeground="black")

            self.Label2_14 = tk.Label(self.Labelframe1)
            self.Label2_14.place(relx=0.36, rely=0.179, height=21, width=54
                                 , bordermode='ignore')
            self.Label2_14.configure(activebackground="#f9f9f9")
            self.Label2_14.configure(activeforeground="black")
            self.Label2_14.configure(background="#d9d9d9")
            self.Label2_14.configure(disabledforeground="#a3a3a3")
            self.Label2_14.configure(foreground="#000000")
            self.Label2_14.configure(highlightbackground="#d9d9d9")
            self.Label2_14.configure(highlightcolor="black")
            self.Label2_14.configure(text='''MFCC 12''')

            self.Label2_15 = tk.Label(self.Labelframe1)
            self.Label2_15.place(relx=0.36, rely=0.269, height=21, width=54
                                 , bordermode='ignore')
            self.Label2_15.configure(activebackground="#f9f9f9")
            self.Label2_15.configure(activeforeground="black")
            self.Label2_15.configure(background="#d9d9d9")
            self.Label2_15.configure(disabledforeground="#a3a3a3")
            self.Label2_15.configure(foreground="#000000")
            self.Label2_15.configure(highlightbackground="#d9d9d9")
            self.Label2_15.configure(highlightcolor="black")
            self.Label2_15.configure(text='''MFCC 13''')

            self.Label2_16 = tk.Label(self.Labelframe1)
            self.Label2_16.place(relx=0.36, rely=0.358, height=21, width=54
                                 , bordermode='ignore')
            self.Label2_16.configure(activebackground="#f9f9f9")
            self.Label2_16.configure(activeforeground="black")
            self.Label2_16.configure(background="#d9d9d9")
            self.Label2_16.configure(disabledforeground="#a3a3a3")
            self.Label2_16.configure(foreground="#000000")
            self.Label2_16.configure(highlightbackground="#d9d9d9")
            self.Label2_16.configure(highlightcolor="black")
            self.Label2_16.configure(text='''MFCC 14''')

            self.Label2_17 = tk.Label(self.Labelframe1)
            self.Label2_17.place(relx=0.36, rely=0.448, height=21, width=54
                                 , bordermode='ignore')
            self.Label2_17.configure(activebackground="#f9f9f9")
            self.Label2_17.configure(activeforeground="black")
            self.Label2_17.configure(background="#d9d9d9")
            self.Label2_17.configure(disabledforeground="#a3a3a3")
            self.Label2_17.configure(foreground="#000000")
            self.Label2_17.configure(highlightbackground="#d9d9d9")
            self.Label2_17.configure(highlightcolor="black")
            self.Label2_17.configure(text='''MFCC 15''')

            self.Label2_18 = tk.Label(self.Labelframe1)
            self.Label2_18.place(relx=0.36, rely=0.537, height=21, width=54
                                 , bordermode='ignore')
            self.Label2_18.configure(activebackground="#f9f9f9")
            self.Label2_18.configure(activeforeground="black")
            self.Label2_18.configure(background="#d9d9d9")
            self.Label2_18.configure(disabledforeground="#a3a3a3")
            self.Label2_18.configure(foreground="#000000")
            self.Label2_18.configure(highlightbackground="#d9d9d9")
            self.Label2_18.configure(highlightcolor="black")
            self.Label2_18.configure(text='''MFCC 16''')

            self.Label2_19 = tk.Label(self.Labelframe1)
            self.Label2_19.place(relx=0.36, rely=0.627, height=21, width=54
                                 , bordermode='ignore')
            self.Label2_19.configure(activebackground="#f9f9f9")
            self.Label2_19.configure(activeforeground="black")
            self.Label2_19.configure(background="#d9d9d9")
            self.Label2_19.configure(disabledforeground="#a3a3a3")
            self.Label2_19.configure(foreground="#000000")
            self.Label2_19.configure(highlightbackground="#d9d9d9")
            self.Label2_19.configure(highlightcolor="black")
            self.Label2_19.configure(text='''MFCC 17''')

            self.Label2_20 = tk.Label(self.Labelframe1)
            self.Label2_20.place(relx=0.36, rely=0.716, height=21, width=54
                                 , bordermode='ignore')
            self.Label2_20.configure(activebackground="#f9f9f9")
            self.Label2_20.configure(activeforeground="black")
            self.Label2_20.configure(background="#d9d9d9")
            self.Label2_20.configure(disabledforeground="#a3a3a3")
            self.Label2_20.configure(foreground="#000000")
            self.Label2_20.configure(highlightbackground="#d9d9d9")
            self.Label2_20.configure(highlightcolor="black")
            self.Label2_20.configure(text='''MFCC 18''')

            self.Label2_21 = tk.Label(self.Labelframe1)
            self.Label2_21.place(relx=0.36, rely=0.806, height=21, width=54
                                 , bordermode='ignore')
            self.Label2_21.configure(activebackground="#f9f9f9")
            self.Label2_21.configure(activeforeground="black")
            self.Label2_21.configure(background="#d9d9d9")
            self.Label2_21.configure(disabledforeground="#a3a3a3")
            self.Label2_21.configure(foreground="#000000")
            self.Label2_21.configure(highlightbackground="#d9d9d9")
            self.Label2_21.configure(highlightcolor="black")
            self.Label2_21.configure(text='''MFCC 19''')

            self.Label2_22 = tk.Label(self.Labelframe1)
            self.Label2_22.place(relx=0.36, rely=0.896, height=21, width=54
                                 , bordermode='ignore')
            self.Label2_22.configure(activebackground="#f9f9f9")
            self.Label2_22.configure(activeforeground="black")
            self.Label2_22.configure(background="#d9d9d9")
            self.Label2_22.configure(disabledforeground="#a3a3a3")
            self.Label2_22.configure(foreground="#000000")
            self.Label2_22.configure(highlightbackground="#d9d9d9")
            self.Label2_22.configure(highlightcolor="black")
            self.Label2_22.configure(text='''MFCC 20''')

            self.Label2_23 = tk.Label(self.Labelframe1)
            self.Label2_23.place(relx=0.674, rely=0.09, height=21, width=54
                                 , bordermode='ignore')
            self.Label2_23.configure(activebackground="#f9f9f9")
            self.Label2_23.configure(activeforeground="black")
            self.Label2_23.configure(background="#d9d9d9")
            self.Label2_23.configure(disabledforeground="#a3a3a3")
            self.Label2_23.configure(foreground="#000000")
            self.Label2_23.configure(highlightbackground="#d9d9d9")
            self.Label2_23.configure(highlightcolor="black")
            self.Label2_23.configure(text='''Chroma''')

            self.Label2_24 = tk.Label(self.Labelframe1)
            self.Label2_24.place(relx=0.663, rely=0.179, height=21, width=54
                                 , bordermode='ignore')
            self.Label2_24.configure(activebackground="#f9f9f9")
            self.Label2_24.configure(activeforeground="black")
            self.Label2_24.configure(background="#d9d9d9")
            self.Label2_24.configure(disabledforeground="#a3a3a3")
            self.Label2_24.configure(foreground="#000000")
            self.Label2_24.configure(highlightbackground="#d9d9d9")
            self.Label2_24.configure(highlightcolor="black")
            self.Label2_24.configure(text='''RMSE''')

            self.Label2_25 = tk.Label(self.Labelframe1)
            self.Label2_25.place(relx=0.669, rely=0.269, height=21, width=104
                                 , bordermode='ignore')
            self.Label2_25.configure(activebackground="#f9f9f9")
            self.Label2_25.configure(activeforeground="black")
            self.Label2_25.configure(background="#d9d9d9")
            self.Label2_25.configure(disabledforeground="#a3a3a3")
            self.Label2_25.configure(foreground="#000000")
            self.Label2_25.configure(highlightbackground="#d9d9d9")
            self.Label2_25.configure(highlightcolor="black")
            self.Label2_25.configure(text='''Spectral Centroid''')
            self.Label2_25.configure(width=104)

            self.Label2_26 = tk.Label(self.Labelframe1)
            self.Label2_26.place(relx=0.674, rely=0.358, height=21, width=104
                                 , bordermode='ignore')
            self.Label2_26.configure(activebackground="#f9f9f9")
            self.Label2_26.configure(activeforeground="black")
            self.Label2_26.configure(background="#d9d9d9")
            self.Label2_26.configure(disabledforeground="#a3a3a3")
            self.Label2_26.configure(foreground="#000000")
            self.Label2_26.configure(highlightbackground="#d9d9d9")
            self.Label2_26.configure(highlightcolor="black")
            self.Label2_26.configure(text='''Spectral Bandwidh''')
            self.Label2_26.configure(width=104)

            self.Label2_27 = tk.Label(self.Labelframe1)
            self.Label2_27.place(relx=0.674, rely=0.448, height=21, width=84
                                 , bordermode='ignore')
            self.Label2_27.configure(activebackground="#f9f9f9")
            self.Label2_27.configure(activeforeground="black")
            self.Label2_27.configure(background="#d9d9d9")
            self.Label2_27.configure(disabledforeground="#a3a3a3")
            self.Label2_27.configure(foreground="#000000")
            self.Label2_27.configure(highlightbackground="#d9d9d9")
            self.Label2_27.configure(highlightcolor="black")
            self.Label2_27.configure(text='''Zero Crossing''')
            self.Label2_27.configure(width=84)

            self.EntryChroma = tk.Entry(self.Labelframe1)
            self.EntryChroma.place(relx=0.826, rely=0.09, height=20, relwidth=0.156
                                   , bordermode='ignore')
            self.EntryChroma.configure(background="white")
            self.EntryChroma.configure(disabledforeground="#a3a3a3")
            self.EntryChroma.configure(font=font10)
            self.EntryChroma.configure(foreground="#000000")
            self.EntryChroma.configure(highlightbackground="#d9d9d9")
            self.EntryChroma.configure(highlightcolor="black")
            self.EntryChroma.configure(insertbackground="black")
            self.EntryChroma.configure(selectbackground="#c4c4c4")
            self.EntryChroma.configure(selectforeground="black")
            self.EntryChroma.configure(width=134)

            self.EntryRMSE = tk.Entry(self.Labelframe1)
            self.EntryRMSE.place(relx=0.826, rely=0.179, height=20, relwidth=0.156
                                   , bordermode='ignore')
            self.EntryRMSE.configure(background="white")
            self.EntryRMSE.configure(disabledforeground="#a3a3a3")
            self.EntryRMSE.configure(font=font10)
            self.EntryRMSE.configure(foreground="#000000")
            self.EntryRMSE.configure(highlightbackground="#d9d9d9")
            self.EntryRMSE.configure(highlightcolor="black")
            self.EntryRMSE.configure(insertbackground="black")
            self.EntryRMSE.configure(selectbackground="#c4c4c4")
            self.EntryRMSE.configure(selectforeground="black")

            self.EntryCentroid = tk.Entry(self.Labelframe1)
            self.EntryCentroid.place(relx=0.826, rely=0.269, height=20, relwidth=0.156
                                   , bordermode='ignore')
            self.EntryCentroid.configure(background="white")
            self.EntryCentroid.configure(disabledforeground="#a3a3a3")
            self.EntryCentroid.configure(font=font10)
            self.EntryCentroid.configure(foreground="#000000")
            self.EntryCentroid.configure(highlightbackground="#d9d9d9")
            self.EntryCentroid.configure(highlightcolor="black")
            self.EntryCentroid.configure(insertbackground="black")
            self.EntryCentroid.configure(selectbackground="#c4c4c4")
            self.EntryCentroid.configure(selectforeground="black")

            self.EntryBandwidth = tk.Entry(self.Labelframe1)
            self.EntryBandwidth.place(relx=0.826, rely=0.358, height=20, relwidth=0.156
                                   , bordermode='ignore')
            self.EntryBandwidth.configure(background="white")
            self.EntryBandwidth.configure(disabledforeground="#a3a3a3")
            self.EntryBandwidth.configure(font=font10)
            self.EntryBandwidth.configure(foreground="#000000")
            self.EntryBandwidth.configure(highlightbackground="#d9d9d9")
            self.EntryBandwidth.configure(highlightcolor="black")
            self.EntryBandwidth.configure(insertbackground="black")
            self.EntryBandwidth.configure(selectbackground="#c4c4c4")
            self.EntryBandwidth.configure(selectforeground="black")

            self.EntryZeroCross = tk.Entry(self.Labelframe1)
            self.EntryZeroCross.place(relx=0.826, rely=0.448, height=20, relwidth=0.156
                                   , bordermode='ignore')
            self.EntryZeroCross.configure(background="white")
            self.EntryZeroCross.configure(disabledforeground="#a3a3a3")
            self.EntryZeroCross.configure(font=font10)
            self.EntryZeroCross.configure(foreground="#000000")
            self.EntryZeroCross.configure(highlightbackground="#d9d9d9")
            self.EntryZeroCross.configure(highlightcolor="black")
            self.EntryZeroCross.configure(insertbackground="black")
            self.EntryZeroCross.configure(selectbackground="#c4c4c4")
            self.EntryZeroCross.configure(selectforeground="black")



if __name__ == '__main__':
    vp_start_gui()





